# Maximum translational velocity
# If set to 0.0, this is not considered and default values from the mapi configuration will be used.
float64 max_trans_vel 0.0

# Maximum translational acceleration
# If set to 0.0, this is not considered and default values from the mapi configuration will be used.
float64 max_trans_acc 0.0

# Maximum translational deceleration
# If set to 0.0, this is not considered and default values from the mapi configuration will be used.
float64 max_trans_dec 0.0

# Maximum rotational velocity
# If set to 0.0, this is not considered and default values from the mapi configuration will be used.
float64 max_rot_vel 0.0
