# Plan and execute a motion to a joint configuration

# Joint model group to use
# If this is empty, a default group is assumed. This is only possible if there is exactly one group in robot_description_semantic that is not designated as an end-effector.
string joint_group

# Joint positions
# This needs to match up with the number of active joints in joint_group.
float64[] positions

# Motion parameters to use during execution
# If left unchanged, defaults from mapi configuration will be used.
MotionParameters motion_parameters

# Controller to use for trajectory execution
# If left empty, a default controller is used
string controller
---
bool success
string message
---
Progress progress
